export const featuredContent = {
  id: 'featured-1',
  title: 'The Last Kingdom',
  subtitle: 'An epic tale of power, honor, and destiny',
  description: 'Experience the dramatic conclusion of a legendary saga as heroes clash in a battle for ultimate supremacy.',
  image: 'https://images.pexels.com/photos/32694014/pexels-photo-32694014.jpeg',
  genre: 'Drama',
  year: 2024,
  rating: 'PG-13',
}

export const contentLibrary = [
  {
    id: '1',
    title: 'The Crown Jewels',
    genre: 'Drama',
    rating: 'PG-13',
    year: 2024,
    image: 'https://images.pexels.com/photos/31361935/pexels-photo-31361935.jpeg',
    description: 'A royal family\'s secrets unravel in this compelling drama series.',
  },
  {
    id: '2',
    title: 'Echoes of Tomorrow',
    genre: 'Sci-Fi',
    rating: 'PG',
    year: 2024,
    image: 'https://images.pexels.com/photos/7651032/pexels-photo-7651032.jpeg',
    description: 'Humanity\'s last hope lies in a desperate mission across the stars.',
  },
  {
    id: '3',
    title: 'Midnight Mystery',
    genre: 'Thriller',
    rating: '16',
    year: 2023,
    image: 'https://images.pexels.com/photos/13617992/pexels-photo-13617992.jpeg',
    description: 'A detective races against time to solve a baffling case.',
  },
  {
    id: '4',
    title: 'Love in Paris',
    genre: 'Romance',
    rating: 'PG',
    year: 2024,
    image: 'https://images.pexels.com/photos/30704104/pexels-photo-30704104.jpeg',
    description: 'Two strangers meet in the City of Light and discover magic.',
  },
  {
    id: '5',
    title: 'Wild Frontiers',
    genre: 'Adventure',
    rating: 'PG-13',
    year: 2023,
    image: 'https://images.pexels.com/photos/9695924/pexels-photo-9695924.jpeg',
    description: 'Explore untamed lands and discover civilizations long forgotten.',
  },
  {
    id: '6',
    title: 'Digital Noir',
    genre: 'Sci-Fi Thriller',
    rating: '18',
    year: 2024,
    image: 'https://images.pexels.com/photos/7900581/pexels-photo-7900581.jpeg',
    description: 'In a cyberpunk world, a hacker uncovers a dangerous conspiracy.',
  },
  {
    id: '7',
    title: 'Ancient Codes',
    genre: 'Documentary',
    rating: 'G',
    year: 2023,
    image: 'https://images.pexels.com/photos/32610376/pexels-photo-32610376.jpeg',
    description: 'Discover the mysteries hidden in history\'s greatest puzzles.',
  },
  {
    id: '8',
    title: 'Laugh Track',
    genre: 'Comedy',
    rating: 'PG',
    year: 2024,
    image: 'https://images.pexels.com/photos/11320433/pexels-photo-11320433.jpeg',
    description: 'A hilarious journey through life\'s funniest moments.',
  },
]

export const pricingPlans = [
  {
    id: 'free',
    name: 'Freemium',
    price: 'Free',
    description: 'Enjoy quality entertainment with ads',
    features: [
      'Unlimited streaming with ads',
      'HD (720p) quality',
      'Standard definition on 1 device',
      'Ad-supported scheduled programming',
      'Limited content library',
    ],
    cta: 'Start Watching',
    highlighted: false,
  },
  {
    id: 'standard',
    name: 'Standard',
    price: '$5.99',
    priceDescription: '/month',
    description: 'Ad-supported premium streaming',
    features: [
      'Watch on 2 devices at once',
      'Full HD (1080p) quality',
      'Ad-supported content',
      'Full content library access',
      'Offline downloads',
      'Cancel anytime',
    ],
    cta: 'Subscribe Now',
    highlighted: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: '$9.99',
    priceDescription: '/month',
    description: 'Ad-free ultimate entertainment',
    features: [
      'Watch on 4 devices simultaneously',
      '4K Ultra HD quality',
      'Ad-free streaming',
      'Full content library access',
      'Offline downloads',
      'Family sharing (5 profiles)',
      'Priority customer support',
      'Early access to new content',
    ],
    cta: 'Subscribe Now',
    highlighted: false,
  },
]

export const testimonials = [
  {
    name: 'Sarah M.',
    text: 'Araceli offers amazing content at prices that actually make sense. I\'ve cancelled all my other subscriptions!',
  },
  {
    name: 'James T.',
    text: 'The variety and quality of shows is incredible. Best streaming service I\'ve found.',
  },
  {
    name: 'Maria L.',
    text: 'Finally, a service that values both quality content and affordable pricing. Highly recommend!',
  },
]

export const footerLinks = {
  company: [
    { label: 'About Us', href: '/about' },
    { label: 'Careers', href: '#' },
    { label: 'Press', href: '#' },
    { label: 'Blog', href: '#' },
  ],
  support: [
    { label: 'Help Center', href: '#' },
    { label: 'Contact Us', href: '#' },
    { label: 'Account Settings', href: '#' },
    { label: 'Devices', href: '#' },
  ],
  legal: [
    { label: 'Privacy Policy', href: '#' },
    { label: 'Terms of Service', href: '#' },
    { label: 'Cookie Preferences', href: '#' },
  ],
  connect: [
    { label: 'Facebook', href: 'https://www.facebook.com/profile.php?id=61587281891229' },
    { label: 'Twitter', href: '#' },
    { label: 'Instagram', href: '#' },
    { label: 'YouTube', href: '#' },
  ],
}
